//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Conta")]
    public class Conta
    {
        public Conta()
        {
            this.Contato = new HashSet<Contato>();
        }

        [Key]
        public int IdConta { get; set; }
        public string Login { get; set; }
        public string Senha { get; set; }
    
        public virtual ICollection<Contato> Contato { get; set; }
    }
}
